services:
  cryptoserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5